name: break-a-scene
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - accelerate=0.19.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h5764c6d_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=py310h7516544_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - blas=1.0=mkl
  - boost-cpp=1.65.1=0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cffi=1.15.0=py310h0fdd8cc_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.12.0=py_0
  - dill=0.3.6=pyhd8ed1ab_1
  - filelock=3.12.0=pyhd8ed1ab_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2023.5.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.5.0=h48cff8f_0
  - grpc-cpp=1.46.1=h33aed49_1
  - huggingface_hub=0.15.1=py_0
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - joblib=1.2.0=pyhd8ed1ab_0
  - krb5=1.19.4=h568e23c_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcurl=7.88.1=h91b91d3_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=he6d91bd_0
  - libuuid=1.41.5=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - multidict=6.0.2=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.8.4=py310h85018f9_1
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openssl=1.1.1t=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.3=py310h1128e8f_0
  - pip=23.0.1=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - pyarrow=11.0.0=py310h468efa6_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.11=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=cpu_py310ha02dd7b_1
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - sacremoses=master=py_0
  - setuptools=67.8.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.11.4=py310h3dcd8bd_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - transformers=4.28.1=py_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - utf8proc=2.6.1=h27cfd23_0
  - wheel=0.38.4=py310h06a4308_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - cchardet==2.1.7
      - certifi==2023.5.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - diffusers==0.12.1
      - huggingface-hub==0.15.1
      - opencv-python==4.7.0.68
      - pillow==9.5.0
      - regex==2023.6.3
      - urllib3==2.0.3
